### ISSUE TITLE
Question, does this code work with MLX906?

### ISSUE THREAD

**Issue by Hellis81** [tiaanv/esphome_gy601#1]
I'm looking for an IR termometer to ESPHome and I found this.
But I can't find a gy906, only a MLX90614ESF-BAA-000-TU, will this code work for that sensor?
https://www.digikey.se/product-detail/en/melexis-technologies-nv/MLX90614ESF-BAA-000-TU/MLX90614ESF-BAA-000-TU-ND/1647941

**Comment by tiaanv** [comment]
There are a couple of types of these sensors, and it seems this one uses i2c rather than serial. This code was written for the serial implementation that  the board I had worked with.
https://www.ebay.com/itm/GY-MCU90614-BCC-Serial-IR-Non-contact-Infrared-Temperature-Measurement-Module-/172946326062

I  not sure the protocol is the same.  If you have the skills, you should be able to adapt this code appropriately. 
I had a quick look, and my local supplier does not have this version, so I unfortunately won't be able to assist.

**Comment by Hellis81** [comment]
I have never done that kind of coding.
I found this one that is serial. https://www.ebay.com/itm/5V-Infrared-Non-contact-Temperature-Measuring-Sensor-Module-MLX90614-BBA-Sensor/143576381577?pageci=b8647f70-b740-415e-ac77-595906307e40
The only downside is the read distance of it. It (probably) needs 5 cm. I was hoping of almost contact.

**Comment by tiaanv** [comment]
this one has a different protocol also...
Most of the ones I have worked with have a minimum range.  Just out of interest. Why do you require non-contact if you need such a close range?

**Comment by Hellis81** [comment]
As you know.... We all want Home Assistant to display the coffee temperature :-)

The thing is there is too much gap between the walls of my coffee machine and the pot for a contact to be sure. I can put 2-3 contact sensors out a bit from the wall but I think a small hole and contactless is more attractive.
And 5 cm or even 3 cm is too much space to waste in my in my already quite full coffee machine.

But I guess have to go back to contact sensors then.

Thank you for your help!

**Comment by tiaanv** [comment]
I think most non-contact sensors would probably work at that range, the min distance is really to not expose the device to excessive temperatures within the operational reading range. I have tested min at VERY close range, and it had almost no impact on reading accuracy.

**Comment by Hellis81** [comment]
That makes sense.
Why didn't I think of that.
Ok so back to non contact again. Good thing I haven't ordered anything yet.

I found someone at the Home Assistant community that has a I2C "library". 
Since this type you have are hard to find I will go for I2C. 
Thank you for your help! Much appreciated!

**Comment by ztormstiql** [comment]
Could you point me to this library? I would love to use it...
Thanks in advance!

**Comment by ztormstiql** [comment]
I found it on the Home Assistant Community forum :) This is the post if people want to use it: https://community.home-assistant.io/t/meteorological-visibility-from-a-sensor/185936/9 
And the latest version on GitHub: https://github.com/exxamalte/esphome-customisations/blob/master/mlx90614

**Comment by UJStudio** [comment]
Hi Sir, 
I’m newbie on ESPhome custom components and not very familiar with C++. I have a dehumidifier with a serial communication interface, want integrate HASSIO by ESPhome. Trying to learn your code, and reference to others on github, after week trying but unfortunately fail until now, came look for your help.

I can get message by Serial Debugger Tools:
send { 0x01, 0x03, 0x00, 0x2A, 0x00, 0x02, 0xE5, 0xC3 }
respond { 01 03 04 00 50 00 3C FA 33}
00, 50, 00, 3C this 4 bytes are factory set value, RH 60% （0x3C) stop, RH 80% (0x50) start.
send { 0x01, 0x03, 0x00, 0x30, 0x00, 0x05, 0x85, 0xC6 }
respond { 01 03 0A 00 15 00 3F 00 15 00 15 00 04 04 E1 }
first 00, 15 will be detected ambient temperature 21°C; 00, 3F will be detected relative humidity 63 RH%; second and third 00, 15, 00, 15 will be the semicon refrigeration board cool side 21°C, hot side 21°C(machine suspend now); 00, 04 is the machine working status, (4 or 0 = suspend, 3 = on)

Want to have these 7 sensors and update every 10 seconds, looking forward your assist or advise.
